version: 2.1
jobs:
  build:
    working_directory: ~/obsolete-webpack-plugin
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm run bootstrap
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint Code
          command: npm run lint
      - run:
          name: Build Artifact
          command: npm run build
      - run:
          name: Pass Test
          command: npm run test:coverage
workflows:
  version: 2
  build:
    jobs:
      - build
