version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Working Directory
          command: pwd
      - run:
          name: Install Dependencies
          command: npm run bootstrap
      - run:
          name: Code Lint
          command: npm run lint
      - run:
          name: Build Artifact
          command: npm run build
      - run:
          name: Test Pass
          command: npm test:coverage
workflows:
  version: 2
  build:
    jobs:
      - build
