version: 2.1
commands:
  build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: Prepare Stage
          command: npm run bootstrap
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint Stage
          command: npm run lint
      - run:
          name: Build Stage
          command: npm run build
      - run:
          name: Test Stage
          command: npm run test:cover
      - run:
          name: Upload Reporter
          command: npm run test:report
jobs:
  node-7:
    docker:
      - image: circleci/node:7
    steps:
      - build
  node-8:
    docker:
      - image: circleci/node:8
    steps:
      - build
  node-10:
    docker:
      - image: circleci/node:10
    steps:
      - build
  node-11:
    docker:
      - image: circleci/node:11
    steps:
      - build
workflows:
  parallel-build:
    jobs:
      - node-7
      - node-8
      - node-10
      - node-11

